version: '3.8'

services:
  smct-app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smct-app1
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./storage:/var/www/html/storage
      - ./public/style.css:/var/www/html/public/style.css
    networks:
      - smct-app1-network

  smct-app1-nginx:
    image: nginx:alpine
    container_name: smct-app1-nginx
    restart: unless-stopped
    ports:
      - "1005:1005"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./storage:/var/www/html/storage
      - ./public/style.css:/var/www/html/public/style.css
    networks:
      - smct-app1-network
    depends_on:
      - smct-app1

networks:
  smct-app1-network:
    driver: bridge